apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: promote-manual-pipeline-run-
  namespace: coffeeshop-pipelines
spec:
  serviceAccountName: pipeline-service-account
  timeout: "1h0m0s"  
  pipelineRef:
    name: promote-pipeline
  resources:
    - name: gitops-dest
      resourceRef:
        name: gitops-staging-repo
    - name: gitops-source
      resourceRef:
        name: gitops-dev-repo    
  params:
    - name: service
      value: coffeeshop-ui    
    - name: git-user
      value: "Coffeeshop pipeline"    
    - name: git-email
      value: "coffeeshop-pipeline@ibm.com"   
