apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-clusterrole
rules:
  - apiGroups:
      - appsody.dev
    resources:
      - appsodyapplications
    verbs: 
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps.openshift.io
    resources:
      - servicebindingrequests
    verbs: 
      - get
      - create
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-clusterrole
subjects:
  - kind: ServiceAccount
    name: pipeline-service-account
    namespace: coffeeshop-pipelines
