apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
  namespace: coffeeshop-pipelines
spec:
  serviceAccountName: pipeline-service-account
  triggers:
    - name: dev-trigger
      interceptors:
        - cel:
            filter: "header.match('X-GitHub-Event','push') && body.ref == 'refs/heads/master' && body.repository.name == 'gitops-dev'"
      bindings:
        - name: dev-binding
        - name: git-binding
      template:
        name: pipeline-template
    - name: staging-trigger
      interceptors:
        - cel:
            filter: "header.match('X-GitHub-Event','push') && body.ref == 'refs/heads/master' && body.repository.name == 'gitops-staging'"
      bindings:
        - name: staging-binding
        - name: git-binding
      template:
        name: pipeline-template
    - name: build-trigger
      interceptors:
        - cel:
            filter: "header.match('X-GitHub-Event','push') && body.ref == 'refs/heads/master' && !(body.repository.name.startsWith('gitops'))"
      bindings:
        - name: git-binding
      template:
        name: build-pipeline-template
