apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-trigger-roles
  namespace: coffeeshop-pipelines
rules:
# Permissions for every EventListener deployment to function
  - apiGroups: 
      - tekton.dev
    resources: 
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - tasks
      - taskruns
    verbs: 
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs: 
      - get
      - list
      - watch
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: 
      - tekton.dev
    resources: 
      - pipelineruns
      - pipelineresources
    verbs: 
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rolebinding
  namespace: coffeeshop-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-trigger-roles
subjects:
  - kind: ServiceAccount
    name: pipeline-service-account
    namespace: coffeeshop-pipelines
