apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
  namespace: coffeeshop-pipelines
spec:
  params:
    - name: message
      default: "Default message"
    - name: gitrevision
    - name: giturl
    - name: ns
      description: The namespace to deploy into
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: run-deploy-pipeline-$(params.ns)-
        namespace: coffeeshop-pipelines
      spec:
        serviceAccountName: pipeline-service-account
        pipelineRef:
          name: pipeline-deploy
        resources:
          - name: git-source
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(params.gitrevision)
              - name: url
                value: $(params.giturl)
        params:
          - name: message
            value: $(params.message)
          - name: ns
            value: $(params.ns)
