apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: promote-task
  namespace: coffeeshop-pipelines
spec:
  inputs:
    resources:
      - name: gitops-dest
        type: git
      - name: gitops-source
        type: git  
    params:
      - name: service
        type: string
      - name: git-user
        type: string
      - name: git-email
        type: string
  steps:
    - name: promote
      image: docker.io/matthewpwilson/hub
      script: |
        #!/usr/bin/env sh
        set -e

        git config --global user.email "$(inputs.params.git-email)"
        git config --global user.name "$(inputs.params.git-user)"
        git config --global --add hub.host github.ibm.com
        GITHUB_HOST=github.ibm.com

        cd "/workspace/$gitops_source"
        branch=`git rev-parse HEAD | cut -c-6`
       
        cd "/workspace/$gitops_dest/services/$(inputs.params.service)/base"
        git checkout -b $branch
        rm -fr config 
        cp -R "/workspace/$gitops_source/services/$(inputs.params.service)/base/config" .
        cp "/workspace/$gitops_source/services/$(inputs.params.service)/base/kustomization.yaml" .  
        
        message="Promoting $(inputs.params.service) from promote pipeline"
        git add -A .
        git commit -m "$message"
        git push origin $branch
        hub pull-request -m "$message"
      env:
        - name: gitops_dest
          value: gitops-dest
        - name: gitops_source
          value: gitops-source  
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-auth  
              key: password
